# PUBLISH A PACKAGE TO GITHUB CONTAINER REGISTRY. REQUIRES A DOCKERFILE IN THE PROJECT
# ROOT FOLDER.
# ADDING "-beta" SUFFIX IN THE VERSION IN "version" PROPERTY DEFINES A BETA/TEST TAG AND
# WON'T BE BUILT.

name: Publish to Github Container Registry

on:
  push:
    branches:
      - main

env:
  SUFFIX: -beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "✅ Checkout code"
        uses: actions/checkout@master

      - name: "📦 Extracting version from package.json"
        id: get-package-version
        uses: jaywcjlove/github-action-package@main

      - name: "📜 Printing package version"
        run: echo ${{ steps.get-package-version.outputs.version }}

      - name: "🏷️ Gathering tag name removing timestamp"
        if: ${{ !contains(steps.get-package-version.outputs.version, env.SUFFIX) }}
        id: get-ver
        run: |
          ver=$(echo ${{ steps.get-package-version.outputs.version }} | cut -d- -f1)
          echo "::set-output name=ver::$ver"

      - name: "🐳 Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "🐳 Build and Push to GitHub Container Registry"
        if: ${{ !contains(steps.get-package-version.outputs.version, env.SUFFIX) }}
        run: |
          docker build . --tag ghcr.io/dexdevlab/nextjs-webapp-kit:latest
          docker push ghcr.io/dexdevlab/nextjs-webapp-kit:latest
